routes/web.php
<?php

Route::get('/', function () {
    return redirect('/home');
});

// Route::get('/', function () {
//     return redirect('/me');
// });

Route::get('/me', 'MeController@index');

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);
});

resources/views/partials/analytics.blade.php
@if (env('APP_ENV') == 'production')
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-88453232-1', 'auto');
        ga('send', 'pageview');

    </script>
@endif

resources/views/partials/head.blade.php
<meta charset="utf-8">
<title>
    Quiz Master - powered by QuickAdminPanel.com
</title>

<meta http-equiv="X-UA-Compatible"
      content="IE=edge">
<meta content="width=device-width, initial-scale=1.0"
      name="viewport"/>
<meta http-equiv="Content-type"
      content="text/html; charset=utf-8">

<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all"
      rel="stylesheet"
      type="text/css"/>
<link rel="stylesheet"
      href="{{ url('quickadmin/css') }}/font-awesome.min.css"/>
<link rel="stylesheet"
      href="{{ url('quickadmin/css') }}/bootstrap.min.css"/>
<link rel="stylesheet"
      href="{{ url('quickadmin/css') }}/components.css"/>
<link rel="stylesheet"
      href="{{ url('quickadmin/css') }}/quickadmin-layout.css"/>
<link rel="stylesheet"
      href="{{ url('quickadmin/css') }}/quickadmin-theme-default.css"/>
<link rel="stylesheet"
      href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet"
      href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css"/>
<link rel="stylesheet"
      href="https://cdn.datatables.net/select/1.2.0/css/select.dataTables.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.standalone.min.css"/>

<meta property="og:title" content="Quiz Master" />
{{--  <meta property="og:image" content="{{ asset('.png') }}" />  --}}
<meta property="og:description" content="Mini-project with Laravel Quiz. Powered by QuickAdminPanel.com code generator." />

resources/views/partials/header.blade.php
<div class="page-header-inner">
    <div class="page-header-inner">
        <div class="navbar-header">
            <a href="{{ url('/') }}"
               class="navbar-brand">
                @lang('quickadmin.quickadmin_title')
            </a>
        </div>
        <a href="javascript:;"
           class="menu-toggler responsive-toggler"
           data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>

        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

            </ul>
        </div>
    </div>
</div>

resources/views/partials/javascripts.blade.php
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="{{ url('quickadmin/js') }}/bootstrap.min.js"></script>
<script src="{{ url('quickadmin/js') }}/main.js"></script>

<script>
    window._token = '{{ csrf_token() }}';
</script>

@yield('javascript')

resources/views/partials/sidebar.blade.php
@inject('request', 'Illuminate\Http\Request')
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu"
            data-keep-expanded="false"
            data-auto-scroll="true"
            data-slide-speed="200">

            {{--  Quiz Management   --}}
            <li>
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="title">@lang('quickadmin.make-quiz.title')</span>
                    <span class="fa arrow"></span>
                </a>
            <ul class="sub-menu"> 
            <li class="{{ $request->segment(1) == 'cari_perbedaan' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.cari-perbedaan.title')
                            </span>
                        </a>
            </li>

            <li class="{{ $request->segment(1) == 'cari_lokasi' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.cari-lokasi.title')
                            </span>
                        </a>
            </li>

            <li class="{{ $request->segment(1) == 'kecepatan_klik' ? 'active active-sub' : '' }}">
                        <a href=" ">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.kecepatan-klik.title')
                            </span>
                        </a>
            </li>

            <li class="{{ $request->segment(1) == 'ketangkasan_waktu' ? 'active active-sub' : '' }}">
                        <a href=" ">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.ketangkasan-waktu.title')
                            </span>
                        </a>
            </li>

             <li class="{{ $request->segment(1) == 'matematika' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.matematika.title')
                            </span>
                        </a>
            </li>

            <li class="{{ $request->segment(1) == 'memory_test' ? 'active active-sub' : '' }}">
                        <a href="">
                        {{--  <a href="{{ route('questions_options.index') }}">  --}}
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.memory-test.title')
                            </span>
                        </a>
            </li>

            <li class="{{ $request->segment(1) == 'multiple_choice' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.multiple-choice.title')
                            </span>
                        </a>
            </li>



             <li class="{{ $request->segment(1) == 'puzzle' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.puzzle.title')
                            </span>
                        </a>
            </li>


             <li class="{{ $request->segment(1) == 'tebak_logo' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.tebak-logo.title')
                            </span>
                        </a>
            </li>

             <li class="{{ $request->segment(1) == 'tes_kepribadian' ? 'active active-sub' : '' }}">
                        <a href="">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.tes-kepribadian.title')
                            </span>
                        </a>
            </li>
            </ul>
            </li>

            {{--  end  --}}

            
            {{--  <li>
            <a href="#">
                    <i class="fa fa-th-list"></i>
                    <span class="title">@lang('quickadmin.my-quiz.title')</span>
                    <span class="fa arrow"></span>
                </a>
            <ul class="sub-menu">
            <li class="{{ $request->segment(1) == 'tests' ? 'active active-sub' : '' }}">
                <a href="{{ route('tests.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.test.new')</span>
                </a>
            </li>

            <li class="{{ $request->segment(1) == 'results' ? 'active active-sub' : '' }}">
                <a href="{{ route('results.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.results.title')</span>
                </a>
            </li>
            </ul>
            </li>  --}}

            @if(Auth::user()->isAdmin())
            {{--  Quiz Management  --}}
            {{--  <li>
            <a href="#">
                    <i class="fa fa-th-list"></i>
                    <span class="title">@lang('quickadmin.user-management.title')</span>
                    <span class="fa arrow"></span>
            </a>
            <ul class="sub-menu">
            <li class="{{ $request->segment(1) == 'topics' ? 'active' : '' }}">
                <a href="{{ route('topics.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.topics.title')</span>
                </a>
            </li>
            <li class="{{ $request->segment(1) == 'questions' ? 'active' : '' }}">
                <a href="{{ route('questions.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.questions.title')</span>
                </a>
            </li>
            <li class="{{ $request->segment(1) == 'questions_options' ? 'active' : '' }}">
                <a href="{{ route('questions_options.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">@lang('quickadmin.questions-options.title')</span>
                </a>
            </li>
            </ul>
            </li>  --}}
            {{--  end  --}}

            <li>
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="title">@lang('quickadmin.user-management.title')</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="{{ $request->segment(1) == 'roles' ? 'active active-sub' : '' }}">
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-briefcase"></i>
                            <span class="title">
                                @lang('quickadmin.roles.title')
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(1) == 'users' ? 'active active-sub' : '' }}">
                        <a href="{{ route('users.index') }}">
                            <i class="fa fa-user"></i>
                            <span class="title">
                                @lang('quickadmin.users.title')
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(1) == 'user_actions' ? 'active active-sub' : '' }}">
                        <a href="{{ route('user_actions.index') }}">
                            <i class="fa fa-th-list"></i>
                            <span class="title">
                                @lang('quickadmin.user-actions.title')
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
            @endif
            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('quickadmin.logout')</span>
                </a>
            </li>
        </ul>

        <div class="text-center margin-top-20" style="color: white">
            Quiz Master is powered by
            <br />
            KP Adikari 2018
        
            <br /><br />

                  </div>
    </div>
</div>
{!! Form::open(['route' => 'auth.logout', 'style' => 'display:none;', 'id' => 'logout']) !!}
<button type="submit">@lang('quickadmin.logout')</button>
{!! Form::close() !!}

resources/views/partials/topbar.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner">
        <div class="page-header-inner">
            <div class="navbar-header">
                <a href="{{ url('/home') }}"
                   class="navbar-brand">
                    @lang('quickadmin.quickadmin_title')
                </a>
            </div>
            
            <a href="javascript:;"
               class="menu-toggler responsive-toggler"
               data-toggle="collapse"
               data-target=".navbar-collapse">
            </a>

            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">

                </ul>
            </div>
        </div>
    </div>
</div>